spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    jest:
      uris: http://localhost:9200
      read-timeout: 10000
server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.test.mytest.dao
mapper:
    not-empty: true

eureka:
  client:
    service-url:
      defaultZone: http://10.20.20.220:9000/eureka/
    register-with-eureka: false
  instance:
    ip-address: true
